---
name: Vader Integration Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Vim
        run: sudo apt-get install vim neovim

      - name: Download Dependencies
        run: |
          git clone https://github.com/junegunn/vader.vim.git
          wget https://github.com/rgoulter/c-worksheet-instrumentor/releases/download/v0.2.6/c-worksheet-instrumentor-0.2.6.tar
          tar -xf c-worksheet-instrumentor-0.2.6.tar

      - name: Setup Vim Config init.vim
        run: |
          echo <(cat << VIMRC > init.vim
          set rtp+=vader.vim
          set rtp+=.
          filetype plugin indent on
          VIMRC
          )

      - name: Demonstrate C Worksheet
        run: |
          # Uploaded release compiled with recent Java.
          export JAVA_HOME=$JAVA_HOME_21_X64
          c-worksheet-instrumentor-0.2.6/bin/c-worksheet-instrumentor <(cat << EOF
          #include <stdio.h>

          int main(int argc, char **argv) {
            printf("Hello World\n");
          }
          EOF
          )

      - name: Test Vim
        run: |
          # Uploaded release compiled with recent Java.
          export JAVA_HOME=$JAVA_HOME_21_X64
          export PATH=c-worksheet-instrumentor-0.2.6/bin:$PATH
          vim -Es -Nu init.vim -c 'silent Vader! test/*.vader'
        timeout-minutes: 2

      - name: Test NeoVim
        run: |
          # Uploaded release compiled with recent Java.
          export JAVA_HOME=$JAVA_HOME_21_X64
          export PATH=c-worksheet-instrumentor-0.2.6/bin:$PATH
          nvim -Es -u init.vim -c 'silent Vader! test/*.vader'
        timeout-minutes: 2
